import React, {useState} from 'react';
import StripeCheckout from 'react-stripe-checkout';
import axios from 'axios'


const StripeCheckoutForm = ({ total }) => {
  const [loading, setLoading] = useState(false);

  // Function to handle the payment token generated by Stripe
  const handleToken = async (token) => {
    setLoading(true);
    try {
      const response = await axios.post("/api/payment", {
        token,
        amount: total * 100,
      });
      console.log(response.data);
      setLoading(false);
    } catch (error) {
      console.log(error);
      setLoading(false);
    }
  };

  return (
    <div>
      <h1>Checkout</h1>
      <h2>Total: ${total}</h2>
      <StripeCheckout
        token={handleToken}
        stripeKey="pk_test_51N0UqcF1lRcn4KYhkhHSjyqn5evskdxdL3SUCblBPMzcr1ph2BXVCXH7mLeA3PL3JUq12RTAjKXLyymDGot9aj4x00JzbIrte1"
        amount={total * 100}
        currency="USD"
        name="My E-commerce Store"
        description="Payment for My E-commerce Store"
        image="https://www.example.com/logo.png"
      />
      {loading && <p>Loading...</p>}
    </div>
  );
};

export default StripeCheckoutForm;
